import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/components/ui/sidebar";
import AppSidebar from "./AppSidebar";
import CustomTrigger from "./CustomTrigger";

export const metadata: Metadata = {
  title: "Scrib",
  description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`flex min-h-screen ${inter.className}`}>
        <SidebarProvider>
          <AppSidebar />
          <main className="flex-1">
            <CustomTrigger />
            {children}
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
